### PR TITLE
🐛 Fix test compilation

### PR DESCRIPTION
**Pull request by marcelwa**
After merging #8, the project didn't compile locally for me anymore with the error
```
/usr/bin/ld: CMakeFiles/integration_tests.dir/test_iqm_device_integration.cpp.o: undefined reference to symbol '_ZN7testing7MessageC1Ev'
```
indicating issues with name resolution.

This PR consistently uses the guarded `GTest::gtest_main` and `GTest::gtest_mock` link targets, which resolves the issue.

### CODE REVIEW

**Review by burgholzer — APPROVED** [review]
LGTM 👍🏼 
Any idea why the CI is failing?

**Comment by marcelwa** [comment]
> Any idea why the CI is failing?

Not yet. Happens on #7, too, now. I suspect a server-side issue, but I'm not certain yet.

**Comment by burgholzer** [comment]
Seems this was just the Resonance Update to IQM OS 4.5. Re-ran the tests and all is passing now. Merging.
